# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 02:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 1, 2, 9, 14, 743906, tzinfo=utc)),
        ),
    ]
